/* Responsive menu / codex / HUD. DOM for readable text; Canvas for living illustrations. */
const appEl=document.getElementById('app'),hudEl=document.getElementById('hud'),modalEl=document.getElementById('modal');
let codexTab='characters', uiSignature='', activeModal='', lastHUD=0, hudBuilt=false, soundOn=false;
try{const p=JSON.parse(localStorage.getItem('pupil_selection')||'{}');if(CHARACTERS[p.char])selectedChar=p.char;if(HUNTERS[p.hunter])selectedHunter=p.hunter;if(MAP_DEFS[p.map])selectedMapId=p.map;soundOn=localStorage.getItem('pupil_sound')==='1';}catch(_){}
function persistSelection(){try{localStorage.setItem('pupil_selection',JSON.stringify({char:selectedChar,hunter:selectedHunter,map:selectedMapId}));}catch(_){}}
const Soundscape=(()=>{let ac,gain;return{start(){if(!soundOn)return;try{if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();gain=ac.createGain();gain.gain.value=.018;gain.connect(ac.destination);for(const f of [55,82.41,110.1]){const o=ac.createOscillator();o.type='sine';o.frequency.value=f;o.connect(gain);o.start();}}ac.resume();gain.gain.setTargetAtTime(.018,ac.currentTime,.3);}catch(_){}},stop(){if(ac&&gain)gain.gain.setTargetAtTime(0,ac.currentTime,.15);},chime(){if(!ac||!soundOn)return;const o=ac.createOscillator(),g=ac.createGain();o.frequency.setValueAtTime(440,ac.currentTime);o.frequency.exponentialRampToValueAtTime(660,ac.currentTime+.25);g.gain.setValueAtTime(.025,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.4);o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+.4);}}})();
window.Soundscape=Soundscape;
function masthead(){return `<header class="masthead"><button class="brand" data-action="home" aria-label="返回主界面"><span class="brand-eye"></span><span class="brand-name">瞳<small>PUPIL</small></span></button><div class="top-links"><button class="text-button" data-action="help">游玩指南</button><button class="text-button" data-action="settings">设置</button><span class="edition">深空回响 · 03</span></div></header>`;}
function artCanvas(id,kind='char',klass='',map=false){return `<canvas class="${klass}" data-art="${id}" data-kind="${kind}" ${map?'data-map="1"':''} aria-label="${map?MAP_DEFS[id].name:(kind==='hunter'?HUNTERS:CHARACTERS)[id].name}插画"></canvas>`;}
function footer(){return `<footer class="footer-note"><span>PUPIL / A BIO-LUMINOUS WORLD</span><span>八位行者 · 七位追猎者 · <b>五处秘境</b></span></footer>`;}
function homeMarkup(){const c=CHARACTERS[selectedChar],h=HUNTERS[selectedHunter],m=MAP_DEFS[selectedMapId];return `<div class="shell">${masthead()}<section class="hero"><div class="hero-copy"><div class="eyebrow">01 / ASYMMETRIC SURVIVAL</div><h1>在永夜，<br>与<em>微光</em>同行。</h1><p class="hero-description">连接漂泊的蜗灵，编织流动的光。<br>在追猎者的凝望中，唤醒三道共鸣。</p><div class="hero-actions"><button class="primary" data-action="start">进入秘境 <span class="arrow">↗</span></button><button class="secondary" data-action="practice">练习追猎 <span>→</span></button></div></div><div class="hero-art">${artCanvas(selectedChar,'char')}<span class="orbit-label">SPECIMEN / ${c.sub}</span><div class="hero-spec-label"><small>THE WANDERER · ${ROSTER_NOTES[selectedChar].role}</small>${c.name} / ${c.skill.name}</div></div></section><div class="section-line"><h2>本次旅程</h2><span>选择你的行者、对手与秘境</span></div><section class="loadout"><button class="loadout-card" data-action="characters">${artCanvas(selectedChar)}<div><div class="category">行者 / WANDERER</div><strong>${c.name}</strong><small>${c.sub} · ${ROSTER_NOTES[selectedChar].tag}</small></div><span class="chevron">↗</span></button><button class="loadout-card" data-action="hunters">${artCanvas(selectedHunter,'hunter')}<div><div class="category">追猎者 / HUNTER</div><strong>${h.name}</strong><small>${h.sub} · ${ROSTER_NOTES[selectedHunter].tag}</small></div><span class="chevron">↗</span></button><button class="loadout-card" data-action="maps">${artCanvas(selectedMapId,'map','',true)}<div><div class="category">秘境 / SANCTUM</div><strong>${m.name}</strong><small>${m.sub}</small></div><span class="chevron">↗</span></button></section><div class="session-options"><label>游玩方式 <select id="modeSelect" aria-label="游玩方式"><option value="auto" ${enemyMode==='auto'&&!watchMode?'selected':''}>单人 · 自动追猎</option><option value="manual" ${enemyMode==='manual'?'selected':''}>本地双人 · 手动追猎</option><option value="watch" ${watchMode?'selected':''}>双 AI · 观战操练</option></select></label><label>数值偏差 <input id="menuDifficulty" type="range" min="-1" max="1" step=".05" value="${difficultyBias}" aria-label="难度"><span id="difficultyReadout">${difficultyBias<-.3?'舒缓':difficultyBias>.3?'险境':'标准'}</span></label>${aiOptions()}<button class="text-button" data-action="touch">触屏按键 ${showTouchButtons?'开':'关'}</button><button class="text-button" data-action="sound">环境音 ${soundOn?'开':'关'}</button></div>${footer()}</div>`;}
function selectionMarkup(){
 const hunter=codexTab==='hunters', ids=Object.keys(hunter?HUNTERS:CHARACTERS),sel=hunter?selectedHunter:selectedChar,m=(hunter?HUNTERS:CHARACTERS)[sel],note=ROSTER_NOTES[sel];
 const tabs=`<nav class="select-tabs" aria-label="图鉴分类">${[['characters','行者'],['hunters','追猎者'],['maps','秘境']].map(([id,name])=>`<button data-action="${id}" class="${codexTab===id?'active':''}">${name}</button>`).join('')}</nav>`;
 const top=`<div class="select-head"><div><div class="eyebrow">02 / THE CODEX</div><h1>${codexTab==='maps'?'选择秘境':hunter?'选择追猎者':'选择行者'}</h1></div>${tabs}</div>`;
 const bottom=`<div class="select-bottom"><div class="select-summary"><b>${CHARACTERS[selectedChar].name} × ${HUNTERS[selectedHunter].name}</b> / ${MAP_DEFS[selectedMapId].name}<br>连接三只蜗灵，唤醒深空共鸣。</div><div class="hero-actions" style="margin:0"><button class="secondary" data-action="home">返回</button><button class="primary" data-action="start">进入秘境 ↗</button></div></div>`;
 if(codexTab==='maps')return `<div class="shell">${masthead()}${top}<div class="map-grid">${MAP_IDS.map((id,i)=>{const map=MAP_DEFS[id];return `<button class="map-choice ${id===selectedMapId?'selected':''}" data-map-choice="${id}">${artCanvas(id,'map','',true)}<div class="map-copy"><div class="eyebrow">0${i+1} / ${map.sub}<span class="map-status">${id===selectedMapId?'已选择':'↗'}</span></div><h2>${map.name}</h2><p>${map.desc}</p><div class="map-detail">${id==='void'?'开放地形与可穿行薄膜。适合初次旅程，熟悉尾流与联结。':id==='night'?'局部光照与浮游蜗灵。借神坛的微光辨认路径与危险。':id==='buildings'?'加速长板、发光神坛与危墙。利用多层地形改变追逐路线。':map.detail}</div></div></button>`;}).join('')}</div>${bottom}${footer()}</div>`;
 const labels=hunter?['机动','压制','控制']:['机动','联结','生存'];
 return `<div class="shell" style="--spec-rgb:${m.rim}">${masthead()}${top}<section class="selection-layout"><div class="specimen-stage"><span class="stage-number">SPECIMEN / ${String(ids.indexOf(sel)+1).padStart(2,'0')}</span><span class="stage-rarity">${hunter?'THE HUNTER':'THE WANDERER'}</span>${artCanvas(sel,hunter?'hunter':'char','portrait-canvas')}<div class="specimen-caption"><span class="stage-name">${m.name}</span><span class="latin">${m.sub}</span><p>${note.story}</p></div></div><div class="selection-content"><div class="selection-topline"><span>${hunter?'追猎者图鉴':'行者图鉴'}</span><span>${ids.length} SPECIMENS</span></div><div class="roster-grid" role="group" aria-label="${hunter?'追猎者':'行者'}选择">${ids.map(id=>`<button class="roster-card ${id===sel?'selected':''}" data-roster="${id}" aria-pressed="${id===sel}" aria-label="选择${(hunter?HUNTERS:CHARACTERS)[id].name}">${artCanvas(id,hunter?'hunter':'char')}${ROSTER_NOTES[id].fresh?'<span class="new-tag">NEW</span>':''}<strong>${(hunter?HUNTERS:CHARACTERS)[id].name}</strong></button>`).join('')}</div><div class="detail-title"><h2>${note.role}</h2><span class="tag">${note.tag}</span>${note.fresh?'<span class="tag">新增</span>':''}</div><p class="skill-description">${m.skill.effect}</p><div class="skill-row"><span><kbd>${m.skill.key}</kbd>${m.skill.name}</span><span>冷却 <b>${m.skill.charge?m.skill.charge+'s / 充能':m.skill.cd+'s'}</b></span><span>${hunter?'攻击 '+m.atkRange:'速度 '+Math.round(m.speedMul*100)+'%'}</span></div>${m.extraSkill?`<p class="skill-description" style="min-height:0;margin-top:9px;font-size:10px"><kbd>F</kbd> ${m.extraSkill.name} · ${m.extraSkill.effect}</p>`:''}${!hunter&&['wu','jing'].includes(sel)?`<p class="skill-description" style="min-height:0;margin-top:9px;font-size:10px">] ${sel==='wu'?'盲区 · 留下近身视野干扰':'护盾 · 5 秒减伤 50%，增强下次反击'}</p>`:''}<div class="ratings">${labels.map((l,i)=>`<div class="rating">${l}<div class="rating-bar">${[1,2,3,4,5].map(n=>`<i class="${n<=note.ratings[i]?'on':''}"></i>`).join('')}</div></div>`).join('')}</div><p class="tip">玩法提示 / ${note.tip}</p></div></section>${bottom}${footer()}</div>`;
}
function renderApp(){appEl.innerHTML=menuScreen==='main'?homeMarkup():selectionMarkup();prepareArtCanvases();}
function prepareArtCanvases(){for(const c of appEl.querySelectorAll('[data-art]')){const r=c.getBoundingClientRect();c.width=Math.max(1,Math.round(r.width*Math.min(DPR,1.5)));c.height=Math.max(1,Math.round(r.height*Math.min(DPR,1.5)));if(c.dataset.map)PupilArt.map(c.getContext('2d'),c.dataset.art,c.width,c.height);}}
window.addEventListener('resize',()=>{if(gameState==='menu')prepareArtCanvases();});
function animateInterface(){for(const c of appEl.querySelectorAll('[data-art]:not([data-map])')){const g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);const big=c.classList.contains('portrait-canvas')||c.parentElement.classList.contains('hero-art');const r=Math.min(c.width,c.height)*(big?.28:.34);PupilArt.draw(g,c.dataset.art,c.width/2,c.height*(big?.49:.48),r,time,c.dataset.kind);}}
function enterMenu(){gameState='menu';menuScreen='main';setPanelVisible(false);pauseBtnEl.classList.add('hidden');Soundscape.stop();onUp();for(const k in keys)keys[k]=false;activeModal='';uiSignature='';}
function handleAction(action){
 if(action==='home'){enterMenu();renderApp();}
 else if(['characters','hunters','maps'].includes(action)){codexTab=action;menuScreen='adjust';renderApp();}
 else if(action==='start'||action==='practice'){activeModal='';practiceMode=action==='practice';persistSelection();startGame();}
 else if(action==='resume'){gameState='playing';activeModal='';if(soundOn)Soundscape.start();}
 else if(action==='retry'){activeModal='';startGame();}
 else if(action==='help'||action==='settings'||action==='import'){activeModal=action;renderModal();}
 else if(action==='close'){activeModal='';renderModal();}
 else if(action==='touch'){showTouchButtons=!showTouchButtons;savePrefs();syncTouchToggleBtns();renderApp();}
 else if(action==='sound'){soundOn=!soundOn;try{localStorage.setItem('pupil_sound',soundOn?'1':'0');}catch(_){}soundOn?Soundscape.start():Soundscape.stop();renderApp();}
 else if(action==='import-config'){try{applyImportedConfig(JSON.parse(document.getElementById('configInput').value));}catch(_){document.getElementById('importError').textContent='配置无法读取，请检查 JSON 内容。';}}
}
appEl.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.action)handleAction(b.dataset.action);if(b.dataset.roster){codexTab==='hunters'?selectedHunter=b.dataset.roster:selectedChar=b.dataset.roster;persistSelection();renderApp();}if(b.dataset.mapChoice){selectedMapId=b.dataset.mapChoice;persistSelection();renderApp();}});
appEl.addEventListener('change',e=>{if(e.target.id==='modeSelect'){watchMode=e.target.value==='watch';enemyMode=e.target.value==='manual'?'manual':'auto';syncControlPanel();}if(e.target.dataset.aiSide){setAIChoice(e.target);}});
appEl.addEventListener('input',e=>{if(e.target.id==='menuDifficulty'){difficultyBias=Number(e.target.value);savePrefs();document.getElementById('difficultyReadout').textContent=difficultyBias<-.3?'舒缓':difficultyBias>.3?'险境':'标准';}});
modalEl.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)handleAction(b.dataset.action);if(e.target===modalEl&&['help','settings','import'].includes(activeModal)){activeModal='';renderModal();}});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&gameState==='menu'){if(activeModal){activeModal='';renderModal();}else if(menuScreen!=='main'){menuScreen='main';renderApp();}}if(e.key==='Enter'&&gameState==='menu'&&!activeModal&&!e.target.matches('button,input,textarea,select'))handleAction('start');});
function syncControlPanel(){btnAuto.classList.toggle('on',enemyMode==='auto');btnManual.classList.toggle('on',enemyMode==='manual');for(const [slider,value,label] of [[speedSlider,enemySpeedMul,speedVal],[dmgSlider,enemyDmgMul,dmgVal],[rangeSlider,enemyRangeMul,rangeVal],[trailSlider,trailResistMul,trailVal]]){slider.value=value;label.textContent=value.toFixed(2)+'×';}}
function renderModal(){
 modalEl.classList.remove('show-result');
 if(!activeModal){modalEl.innerHTML='';return;}
 let content='';const close='<button class="modal-close" data-action="close" aria-label="关闭">×</button>';
 if(activeModal==='help')content=`${close}<div class="eyebrow">FIELD GUIDE / 01</div><h2>让微光彼此相连</h2><p>靠近蜗灵会逐渐连接，并获得治疗和移动增益。完整连接三只未被催眠的蜗灵即可获胜。持续移动留下尾流，既能加速自己，也会拖慢追猎者。</p><table class="guide-table"><tr><td>行者</td><td>方向键移动 · P 喷尾 · [ 专属技能 · ] 副技能（雾 / 镜）</td></tr><tr><td>追猎者</td><td>WASD 移动 · V 主技能 · E 强化 · F 副技能（部分追猎者）</td></tr><tr><td>暗影</td><td>B：追猎能量充满后召唤 / 拉动暗影</td></tr><tr><td>触屏</td><td>按住空白处拖动；在主界面打开触屏按键。</td></tr><tr><td>练习追猎</td><td>你操纵追猎者，行者自动行动。击败行者获胜。</td></tr></table><p>单人模式由你控制行者。选择“本地双人”后，第二位玩家使用 WASD 控制追猎者。Esc 随时暂停；按住 Tab 查看追逐全景。</p><div class="hero-actions"><button class="primary" data-action="close">准备好了</button></div>`;
 if(activeModal==='settings')content=`${close}<div class="eyebrow">OBSERVATORY / SETTINGS</div><h2>旅程设置</h2><p>游玩方式、难度、触屏按键与环境音可在主界面调整。战斗中右下角的设置可临时调整倍率。</p><p style="margin-top:12px">实验室可调整所有行者、追猎者与全局数值；默认数值提供标准平衡体验。</p><div class="hero-actions"><a class="primary" href="cheat.html" target="_blank" rel="noopener">打开作弊器 ↗</a><button class="secondary" data-action="import">导入配置</button></div><p style="margin-top:15px;font-size:10px">双击文件时，可通过导入配置应用实验室导出的 JSON。</p>`;
 if(activeModal==='import')content=`${close}<div class="eyebrow">BALANCE CONFIG / IMPORT</div><h2>导入实验配置</h2><p>粘贴作弊器导出的 JSON，应用后重新载入游戏。</p><textarea id="configInput" aria-label="配置 JSON" placeholder="粘贴 JSON 配置"></textarea><p id="importError" class="modal-error"></p><div class="hero-actions"><button class="primary" data-action="import-config">应用配置</button></div>`;
 if(activeModal==='intro')content=`<div class="intro-card"><div class="eyebrow">ENTERING / ${currentMapDef.sub}</div><h2>${currentMapDef.name}</h2><p>${watchMode?'双 AI 观战 · 自动操练':practiceMode?'练习追猎 · 你控制追猎者':enemyMode==='auto'?'单人旅程 · 追猎者自动行动':'本地双人 · 一场光与影的追逐'}</p><div class="intro-match"><strong style="color:rgb(${CHARACTERS[selectedChar].rim})">${CHARACTERS[selectedChar].name}</strong><span>×</span><strong style="color:rgb(${HUNTERS[selectedHunter].rim})">${HUNTERS[selectedHunter].name}</strong></div><p>${practiceMode?'阻止行者连接三只蜗灵。':'连接三只蜗灵，让深空重新共鸣。'}</p><div class="intro-progress"><i></i></div></div>`;
 if(activeModal==='paused')content=`<div class="eyebrow">JOURNEY / PAUSED</div><h2>微光暂歇</h2><p>秘境会等你回来。<br>${CHARACTERS[selectedChar].name} × ${HUNTERS[selectedHunter].name} · ${currentMapDef.name}</p><div class="ai-settings">${aiOptions()}</div><div class="hero-actions"><button class="primary" data-action="resume">继续旅程</button><button class="secondary" data-action="home">返回主界面</button></div>`;
 if(activeModal==='win'||activeModal==='dead'){modalEl.classList.add('show-result');modalEl.innerHTML=resultMarkup(activeModal);prepareResult();return;}
 modalEl.innerHTML=`<section class="modal-card" role="dialog" aria-modal="true" aria-label="${activeModal}">${content}</section>`;
}
function syncInterface(){
 const signature=gameState+':'+menuScreen;
 if(signature!==uiSignature){uiSignature=signature;appEl.hidden=gameState!=='menu';hudEl.hidden=gameState==='menu'||['win','dead'].includes(gameState);if(gameState==='menu'){renderApp();activeModal='';Soundscape.stop();}else if(['intro','paused','win','dead'].includes(gameState)){activeModal=gameState;Soundscape.stop();}else{activeModal='';if(soundOn)Soundscape.start();}renderModal();if(!hudBuilt&&gameState!=='menu')buildHUD();}
}
function buildHUD(){hudBuilt=true;hudEl.innerHTML=`<section class="hud-player"><div class="hud-heading"><span id="hudName"></span><small id="hudTime"></small></div><div class="hp-bar"><i id="hudHP"></i></div><div class="hud-numbers"><span id="hudHealth"></span><span id="hudSpeed"></span></div></section><section class="hud-goal">蜗灵共鸣<div class="goal-pips"><i></i><i></i><i></i></div></section><section class="hud-hunter"><div class="hud-heading"><span id="hudHunterName"></span><small>追猎者</small></div><div class="hp-bar"><i id="hudEnemyHP" style="background:#cc9cab"></i></div><div class="hud-numbers"><span id="hudEnemyCD"></span><span id="hudEmpower"></span></div></section><div class="status-chips" id="hudStatuses"></div><div class="hud-skills" id="hudSkills"></div><div class="hud-info" id="hudMap"></div>`;}
function updateHUD(){
 if(performance.now()-lastHUD<100)return;lastHUD=performance.now();if(!hudBuilt)buildHUD();
 const c=CHARACTERS[player.charType],h=HUNTERS[enemy.hunterType];document.getElementById('hudName').textContent=c.name+' / '+c.sub;document.getElementById('hudTime').textContent=Math.floor(matchElapsed/60).toString().padStart(2,'0')+':'+Math.floor(matchElapsed%60).toString().padStart(2,'0');document.getElementById('hudHP').style.width=clamp(player.hp/player.maxHp*100,0,100)+'%';document.getElementById('hudHealth').textContent=Math.max(0,Math.ceil(player.hp))+' / '+player.maxHp+' HP';document.getElementById('hudSpeed').textContent='SPD '+Math.round(Math.hypot(player.vx,player.vy));
 const connected=snails.filter(s=>s.connectProgress>=.999&&s.hypnotized<=.5).length;hudEl.querySelectorAll('.goal-pips i').forEach((p,i)=>p.classList.toggle('on',i<connected));document.getElementById('hudHunterName').textContent=h.name;document.getElementById('hudEnemyHP').style.width=clamp(enemy.hp/enemy.maxHp*100,0,100)+'%';document.getElementById('hudEnemyCD').textContent=enemy.dying?'重新凝聚':h.id==='smoke'?'烟弹 '+enemy.smokeCharges:'V '+(enemy.skillTimer>0?enemy.skillTimer.toFixed(1)+'s':'就绪');document.getElementById('hudEmpower').textContent=enemy.empowered?'已强化':'E '+(enemy.empowerCd>0?Math.ceil(enemy.empowerCd)+'s':'就绪');
 const skills=practiceMode?[['V',h.skill.name,enemy.skillTimer],['E','强化',enemy.empowerCd]]:[['P','喷尾',player.skillCd],['[',c.skill.name,player.charSkillCd]];if(!practiceMode&&['wu','jing'].includes(c.id))skills.push([']',c.id==='wu'?'盲区':'护盾',c.id==='wu'?player.blindCd:player.mirrorKCd]);if(practiceMode&&h.extraSkill)skills.push(['F',h.extraSkill.name,enemy.driftCd]);document.getElementById('hudSkills').innerHTML=skills.map(([key,name,cd])=>`<div class="hud-skill ${cd<=0?'ready':''}"><span class="hud-key">${key}</span><span>${name}<small>${cd>0?cd.toFixed(1)+'s':'READY'}</small></span></div>`).join('');
 const statuses=[];if(player.smokeStacks)statuses.push('烟层 '+player.smokeStacks);if(frostSlow>0||playerFrostTimer>0)statuses.push('霜冻');if(player.tideTimer>0)statuses.push('潮汐加速');if(player.damageReductionTimer>0)statuses.push('折光护盾');if(player.stunTimer>0)statuses.push('失衡');if(shadow.active)statuses.push('暗影催眠 '+shadow.captures+'/'+SHADOW_MAX_CAPTURES);document.getElementById('hudStatuses').textContent=statuses.join(' · ');document.getElementById('hudMap').textContent=currentMapDef.name+' / '+(watchMode?'双 AI 观战':practiceMode?'练习追猎':enemyMode==='auto'?'单人旅程':'本地双人')+' · ESC 暂停';
}
pauseBtnEl.setAttribute('aria-label','暂停或继续游戏');
syncControlPanel();renderApp();

function aiOptions(){return `<label>行者 AI <select data-ai-side="player" aria-label="行者 AI 操练难度">${AI_LEVELS.map((p,i)=>`<option value="${i}" ${i===playerAILevel?'selected':''}>${i+1} · ${p.name}</option>`).join('')}</select></label><label>追猎 AI <select data-ai-side="hunter" aria-label="追猎者 AI 操练难度">${AI_LEVELS.map((p,i)=>`<option value="${i}" ${i===hunterAILevel?'selected':''}>${i+1} · ${p.name}</option>`).join('')}</select></label>`;}
function setAIChoice(el){const n=clamp(Number(el.value)||0,0,4);if(el.dataset.aiSide==='player')playerAILevel=n;else hunterAILevel=n;saveAI();aiBrains[el.dataset.aiSide].think=0;}
modalEl.addEventListener('change',e=>{if(e.target.dataset.aiSide)setAIChoice(e.target);});
